### ISSUE TITLE
Bug: Changing tab crash config

### ISSUE THREAD

**Issue by vpietri** [magento-hackathon/Hackathon_MageMonitoring#25]
Magento ver. 1.9.0.1

"System" > "Monitoring" > "Tab Config"
Drag and drop "PHP Extensions" in the "PHP Information" tab then click on "Save tab config", if cache is not active magento crash instantly

Warning: simplexml_load_string(): Entity: line 45: parser error : StartTag: invalid element name  in /var/www/magento-ruckfield-pro-dev/lib/Varien/Simplexml/Config.php on line 383

#0 [internal function]: mageCoreErrorHandler(2, 'simplexml_load_...', '/var/www/magent...', 383, Array)
#1 /var/www/magento-ruckfield-pro-dev/lib/Varien/Simplexml/Config.php(383): simplexml_load_string('loadCache()
#3 /var/www/magento-ruckfield-pro-dev/app/code/core/Mage/Core/Model/App.php(413): Mage_Core_Model_Config->loadModulesCache()
#4 /var/www/magento-ruckfield-pro-dev/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#5 /var/www/magento-ruckfield-pro-dev/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#6 /var/www/magento-ruckfield-pro-dev/index.php(87): Mage::run('', 'store')
#7 {main}

![selection_005](https://cloud.githubusercontent.com/assets/8598479/4130781/2ba46ad8-333d-11e4-8a04-db30285f0f44.png)

**Comment by diglin** [comment]
I confirm the problem, I work on it.

**Comment by diglin** [comment]
Fix in 9e72ea0aafe629adc3420ba085a95bdf312e5f12
