### ISSUE TITLE
Prepare the source code to respect the coding standard of Firegento

### ISSUE THREAD

**Issue by diglin** [magento-hackathon/Hackathon_MageMonitoring#28]
As mentioned in this ticket #27 we plan to move to the firegento repo. 

The first step is to respect the guidelines of firegento. So we will use the code sniffer standard provided by firegento and update the license as we voted for it. https://github.com/firegento/coding-guidelines/

**Comment by diglin** [comment]
Additionally will be great to close all current open ticket (finish to implement)

**Comment by kortwotze** [comment]
@BWunderlich  and myself are planning to take on this module on the Leipzig Hackathon (@ mm15de) and revitalize it.

I hope to be able to finish most issues, clean the codebase and maybe even improve it further.

**Comment by diglin** [comment]
I'll be there too, so we can join our force

**Comment by Zifius** [comment]
Servus guys, I'll be there too and would like to offer code style fixes to close this task. As I will probably work on some other project if you are planning to overhaul it

**Comment by edannenberg** [comment]
:+1: for cleaning up the current js chart "mess". Running 2 different chart libs in the same extension is kinda silly. Both are not optimal, one doesn't support chart labels, the other is only free for non commercial projects, even though this extension is non commercial, it's save to assume that most Magento stores are not.

http://morrisjs.github.io/morris.js/ looks decent, any other suggestions?

**Comment by diglin** [comment]
@edannenberg the extension is not commercial, so it's not an issue. It's only if we sell the extension but using it a shop even if this one is commercial is not the problem I think.

**Comment by diglin** [comment]
@edannenberg chart.js is MIT license so no issue at all

**Comment by edannenberg** [comment]
@diglin chart.js is not the issue, [devexpress](http://js.devexpress.com/WebDevelopment/Charts/) is, see [skin/js](https://github.com/magento-hackathon/Hackathon_MageMonitoring/tree/master/skin/adminhtml/default/default/monitoring/js)

So if I want to use this chart lib on my commercial site without paying I just create a non commercial thin wrapper and everything is fine and dandy? ;) Not sure it works this way, though I guess you could argue that this extension won't display on the shop frontend. Either way, we need to at least ensure that we comply with their license. Personally I would prefer to use something with a true open source license to avoid any surprises in the future, should be plenty of alternatives around these days.

**Comment by diglin** [comment]
close because the work is done
