### ISSUE TITLE
Rename namespace from "Firegento" to "FireGento"

### ISSUE THREAD

**Issue by therouv** [magento-hackathon/Hackathon_MageMonitoring#31]
The FireGento namespace should be written with an capital G, see https://github.com/firegento/coding-guidelines/blob/master/guidelines/01_MODULE.md#module-naming for reference.

Currently it is written "Firegento" which will cause problems on case-sensitive file systems when other FireGento modules are installed as well.

**Comment by diglin** [comment]
ok fixed 1b13d79
