### ISSUE TITLE
LogWatch mail address should be configurable

### ISSUE THREAD

**Issue by berndwaibel** [magento-hackathon/Hackathon_MageMonitoring#33]
I set up a fresh Magento shop 1.9.1.0 Community Edition (the german one).

It seems the "MageMonitoring Watch Dog Reports" is sent to the address configured as "general mail address".

The generel mail address is used as the contact of the "shop owner".
The watch dog log report is somehow technical, and should be addressed to someone like the "webmaster" or a technical administrative account. Currently it seems to me this could not be configured.

Wishes:
It should be possible to configure the Watchdog mail receiver, without changing the shop owner mail address.

**Comment by edannenberg** [comment]
1. Click gear icon of logging widget
2. ???
3. Profit!

**Comment by berndwaibel** [comment]
Maybe i do not understand the point 2. and 3.
Or I may unable to find Number 1.
Do you mean this one:
![unbenannt](https://cloud.githubusercontent.com/assets/10959449/7835338/6d36542c-0478-11e5-80c3-369dc82b48ab.PNG)

**Comment by diglin** [comment]
I understand that it's not so clear. I had the same issue when I refactored some code. "Default report destination" = "general", general is the main contact of the shop. The other possibilities are "support", "custom1" and "custom2" if I'm not wrong

**Comment by edannenberg** [comment]
You can also enter any email address besides the configured magento contacts.

**Comment by berndwaibel** [comment]
Thanks, i tested it and can commit this:
To use a different mail address for the "Watch Dog report logs" you could enter one of the following values into the "Default report destination" field inside the "Watch Dog Control" found under System->Monitoring:
- general
- sales
- support
- custom1
- custom2
This values are corresponding to the addresses defined inside the "Magento Configuration" as the global store mail addresses.
You could also direct enter a valid mail address here.
Keep in mind to setup up the mailserver connection (under Linux you may install and configure sendmail).
