### ISSUE TITLE
Mage::getEdition() not available

### ISSUE THREAD

**Issue by borriglione** [magento-hackathon/Hackathon_MageMonitoring#43]
Error on opening System -> Monitoring:

Fatal error: Call to undefined method Mage::getEdition() in /home/florianprod/www/vendor/magento-hackathon/hackathon_magemonitoring/app/code/community/Hackathon/MageMonitoring/Model/Widget/System/Abstract.php on line 140 

CE 1.5.1.0 (I know its not the latest....)

**Comment by tecjam** [comment]
This method wasn't availabe until Magento 1.7.

One could use the workaround used in amazon payments module: https://github.com/amzn/amazon-payments-magento-plugin/commit/a9f67c1076ba562462cd28db12390f54ebf8258a

**Comment by edannenberg** [comment]
Should probably use something like https://gist.github.com/jayelkaake/1541793

**Comment by sprankhub** [comment]
Should be fixed with https://github.com/magento-hackathon/Hackathon_MageMonitoring/commit/3836f3fe4d051a576ea31852ab94fcada7c2eb59. Can be closed.

**Comment by diglin** [comment]
closed because fixed
