### ISSUE TITLE
Watch Dogs

### ISSUE THREAD

**Issue by edannenberg** [magento-hackathon/Hackathon_MageMonitoring#9]
Needed some form of notification for log movement so i added a little sub interface called WatchDog. Widgets that implement the new interface have generic magento cron support with individual schedule and some other options. As with widgets other modules can subscribe their watch dogs to this module, useful for report aggregation.

TODO: 
- the email templates are very bare bone, maybe try the responsive templates from: https://github.com/magento-hackathon/Responsive-Email-Templates-with-CSS-Inliner ? Thoughts? Anyone up for that?
- attachments currently not working, refucktored lol.

Pushed everything into new watchdogs branch, you will have to enable the watch dog functionality first via new watch dogs widget on system page, the test button will generate guaranteed reports and a runtime exception.

**Comment by diglin** [comment]
Watch dog is implemented and working. For new feature related to WatchDog create a new one once we moved this repo to Firegento
